import { chromium } from 'playwright-core';
const browser = await chromium.launch({executablePath:'/usr/bin/chromium', headless:false, args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader','--allow-file-access-from-files']});
const page = await browser.newPage({viewport:{width:390,height:844}, deviceScaleFactor:1, isMobile:true, hasTouch:true, locale:'ru-RU'});
const errors=[];
page.on('console', msg => { if (msg.type()==='error') errors.push(`console: ${msg.text()}`); });
page.on('pageerror', err => errors.push(`pageerror: ${err.message}`));
await page.goto('http://127.0.0.1:4173', {waitUntil:'networkidle'});
await page.waitForTimeout(1200);
await page.screenshot({path:'menu.png'});
await page.locator('#start-button').click();
await page.waitForTimeout(350);
await page.screenshot({path:'launch.png'});
const canvas = page.locator('#game-canvas');
const box = await canvas.boundingBox();
if (!box) throw new Error('No canvas');
await page.mouse.move(box.x+box.width/2, box.y+box.height*0.72);
await page.mouse.down();
await page.waitForTimeout(900);
await page.mouse.up();
await page.waitForTimeout(2500);
await page.screenshot({path:'gameplay.png'});
const hudVisible = await page.locator('#hud').isVisible();
const distance = await page.locator('#distance-value').textContent();
console.log(JSON.stringify({hudVisible,distance,errors}, null, 2));
await browser.close();
